name: Checks

on: [push, pull_request]

# For a more complex build matrix example see:
# https://github.com/evandroforks/anki/blob/master/.github/workflows/checks.yml
jobs:

  test:
    name: Tests on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ ubuntu-latest ]

      # Keep all systems running if something fails
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure OS environment variables
        run: |
          set -x
          echo "::set-env name=RELEASE_NAME::1.0.${{ github.run_number }}"

      - name: Create release
        uses: xu-cheng/texlive-action/full@v1
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        with:
          run: |
            set -x
            apk add make unzip zip python3
            make release version="${RELEASE_NAME}"
            unzip "${RELEASE_NAME}"
            cd workspace
            make debug=1
